CREATE TABLE IF NOT EXISTS module_registry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  module_key VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(190) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
