CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(120) NOT NULL UNIQUE,
  full_name VARCHAR(190) NOT NULL,
  role VARCHAR(32) NOT NULL,
  pin_hash VARCHAR(255) NOT NULL,
  branch_id INTEGER NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
