CREATE TABLE IF NOT EXISTS security_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_type VARCHAR(120) NOT NULL,
  level VARCHAR(32) NOT NULL DEFAULT 'warning',
  message TEXT NULL,
  ip_address VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
